package code.shubham.core.order.dao.entities;

public enum OrderStatus {

	CREATED, AWAITING_PAYMENT, CONFIRMED, COMPLETED, CANCELED, INITIATED_REFUND, REFUNDED, SHIPPING, DELIVERED,
	RETURN_INITIATED, RETURNING

}
